jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test
  username: root
  password: root


spring:
  profiles:
    active: abc,def
  mvc:
    view:
      prefix: /WEB-INF/
  redis:
    host: localhost
    port: 6379

  #      配置hikari驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test
    username: root
    password: root

#这样访问项目就不用加上端口了
server:
  port: 80

#设置日志记录级别
logging:
  level:
    com.itheima: debug  #以这个开头的设置为这个级别
    prg.springframework: info


#    配置mybatis
mybatis:
#  对实体类起别名  以后直接写类名即可
  type-aliases-package: com.itheima.pojo
  #  映射文件路径
#  mapper-locations: classpath:mappers/*.xml
#  日志实现
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #后台输出